var APP_NAME = "App Name";
var REALM = "http://...";
var ANAYTICS_ID = "";
var FIREBASEURL = "https://gamestab.firebaseio.com";
var PRELOADER_FLASH_VARS = ""; // flash vars for preloader
var SHOW_PREROLL = true; // show games prerolls
var TITLE = "Website Title";
var FB_APP_ID = "";
var FB_PAGE_URL = ""
var GPLUS_URL ="";
var MAIL_ADDRESS = "";